language: c

arch:
  - amd64
  - arm64
# only gcc
# - s390x big endian
# - ppc64le (gcc > 8.0 sse->altivec)

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - ./icapp ZIPF
#  - cat /proc/cpuinfo
  
matrix:
  include:
    - name: linux-arm64-gcc
      os: linux
      arch: arm64
      compiler: gcc

    - name: windows-mingw-w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
        - ./icapp ZIPF

    - name: apple-macOS-xcode
      os: osx

#    - name: linux-ppc64le-gcc-9
#      arch: ppc64le
#      env: CC=gcc-9
#      before_install:
#        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#        - sudo apt-get -y update
#        - sudo apt-get -y install gcc-9

#    - name: linux-arm64-clang
#      dist: bionic
#      os: linux
#      arch: arm64
#      compiler: clang
#      env: CC=clang-6

#    - name: linux-arm64-clang-7
#      dist: bionic 
#      os: linux
#      arch: arm64
#      addons:
#        apt:
#          update: true
#          sources: *apt_sources
#          packages: [*apt_packages, 'clang-7']
#      env: CC=clang-7

